spring:
  application:
    name: inter-caller-service
  cloud:
    loadbalancer:
      cache:
        ttl: 1s
      ribbon:
        enabled: false

eureka:
  client:
    registryFetchIntervalSeconds: 1

feign:
  client:
    config:
      inter-callme-service:
        readTimeout: 200
        connectTimeout: 200
        loggerLevel: full
